#!/bin/bash

set -e

mkdir -p _zip/chuni/DEVICE

cp  _build32/subprojects/capnhook/inject/inject.exe \
    _build32/aimeio/aimeio.dll \
    _build32/chuniio/chuniio.dll \
    _build32/chunihook/chunihook.dll \
    dist/chuni/segatools.ini \
    dist/chuni/start.bat \
    _zip/chuni/

cp  pki/billing.pub \
    pki/ca.crt \
    _zip/chuni/DEVICE

mkdir -p _zip/idz/DEVICE

cp  _build64/subprojects/capnhook/inject/inject.exe \
    _build64/aimeio/aimeio.dll \
    _build64/idzio/idzio.dll \
    _build64/idzhook/idzhook.dll \
    dist/idz/segatools.ini \
    dist/idz/start.bat \
    _zip/idz/

cp  pki/billing.pub \
    pki/ca.crt \
    _zip/idz/DEVICE

strip _zip/{chuni,idz}/*.{exe,dll}

